version: "3.9"
services:
  app:
    build: .
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    env_file: .env
    depends_on:
      - pg
  pg:
    image: "postgres:alpine"
    ports:
      - "5000:5432"
    environment:
      POSTGRES_DB: typeorm
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: pg
    volumes:
      - ./gen/pg:/var/lib/postgresql/data:delegated
